runtime: python311

instance_class: F2

env_variables:
  PYTHONUNBUFFERED: "TRUE"

handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /.*
    script: auto
    secure: always